### ISSUE TITLE
Solver not Working

### ISSUE THREAD

**Issue by Icabbles** [doxxx/ffxiv-craft-opt-web#141] opened 2017-07-05 17:54 UTC
Since yesterday the Solver is not working for me anymore. Anybody with the same Issue?

**Comment by doxxx** [comment] 2017-07-05 23:18
Can you describe in more detail what happens?

**Comment by Icabbles** [comment] 2017-07-06 03:20
Wether I give him a Crafting Sequence or not as soon as I click on Solve just nothing happens. If I click on the "Start" Button in in the Solver tab, also nothing happens. Tried it with multiple browsers and clearing cache. Nothing changed so far

**Comment by doxxx** [comment] 2017-07-06 03:26
Was it working in the past? Can you think of anything you might have changed since then?

Can you open the browser's developer tools (usually F12) and see if there's any errors in the Console?

**Comment by ZeroSignalDX** [comment] 2017-07-06 04:07
I can duplicate this issue. Have changed no browser settings nor anything in the app itself, confirmed in multiple browsers (Chrome and Firefox). In the Firefox dev console, it has

"ReferenceError: finalState is not defined" from worker.js

Only error shown for me.

**Comment by Icabbles** [comment] 2017-07-06 16:06
worker.js:36 ReferenceError: finalState is not defined
    at postProgress (worker.js:253)
    at runOneGen (worker.js:216)
    at start (worker.js:203)
    at self.onmessage (worker.js:21)

Thats what I´m seeing in the console

**Comment by doxxx** [comment] 2017-07-06 22:18
That's really puzzling. There's no reference to "finalState" in worker.js on any line. I even checked the worker.js that my browser is loading from ffxiv.lokyst.net and it's the same.

The only source file which references "finalState" is simulationworker.js, and the line numbers in that stack trace don't match up with that file either (it's only 148 lines long, for one).

BUT! If you're running the app locally using @ermad's branch for #139, it looks like there's a bug in worker.js where it references finalState instead of currentState.

**Comment by ZeroSignalDX** [comment] 2017-07-06 22:25
I haven't run either yours or Ermad's locally, but it did it using both web apps.

However as of typing this it seems to be working on both branches again.

**Comment by Icabbles** [comment] 2017-07-07 03:20
Can confirm. As of now it´s working again.

**Comment by doxxx** [comment] 2017-07-07 11:51
Thanks. Not sure what was going on there but closing.

**Closed by doxxx** 2017-07-07 11:51 UTC
